apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer
  namespace: kube-system
  labels:
    k8s-app: nvidia-driver-installer
spec:
  selector:
    matchLabels:
      k8s-app: nvidia-driver-installer
  template:
    metadata:
      labels:
        k8s-app: nvidia-driver-installer
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
        operator: "Exists"
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: driver-install-dir
        hostPath:
          path: /home/kubernetes/bin/drivers
      - name: root-mount
        hostPath:
          path: /
      initContainers:
      - image: "cos-nvidia-installer:fixed"
        imagePullPolicy: Never
        name: nvidia-driver-installer
        resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: driver-install-dir
          mountPath: /usr/local/bin/drivers
        - name: root-mount
          mountPath: /root
      containers:
      - image: "gcr.io/google-containers/pause:3.1"
        name: pause
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
